### ISSUE TITLE
UnicodeEncodeError'>, 'charmap' codec can't encode charac ter '\xc3' i

### ISSUE THREAD

**Issue by mstram** [scotws/TaliForth#2]
python 3.4.2 

D:\git\TaliForth\NEW\TaliForth>py65mon --mpu 65C02 -r ophis.bin
Reset with new MPU 65C02

```
    PC  AC XR YR SP NV-BDIZC
```

65C02: 0000 00 00 00 ff 00110000
 Wrote +16384 bytes from $c000 to $ffff

Booting Kernel for the Error: <class 'UnicodeEncodeError'>, 'charmap' codec can't encode charac
ter '\xc3' in position 0: character maps to <undefined>: file: d:\python34\lib\encodings\cp437.
py line: 19

```
    PC  AC XR YR SP NV-BDIZC
```

65C02: e495 c3 00 17 fa 10110100

**Comment by mnaberez** [comment]
See also mnaberez/py65#29.  This error occurred because your terminal is using CP437 encoding but the Tali Forth startup banner sends bytes to the $F001 output handler that aren't compatible with CP437.  I've added a workaround that catches encoding errors and displays `?` instead.  I don't think there's more I can do here, short of adding some feature to allow the 6502 program to specify its character encoding.

Changing the startup banner to emit 7-bit ASCII seems reasonable.  It would be compatible with most modern terminals (UTF-8 and CP437) and, more importantly, the majority of real 6502 target machines.

**Comment by mstram** [comment]
Thanks for the very quick fixes Mike !

It's finally running !

**Comment by scotws** [comment]
On Tue, Feb 10, 2015 at 8:30 AM, Mike Naberezny notifications@github.com
wrote:

Changing the startup banner to emit 7-bit ASCII seems reasonable. It would

> be compatible with most modern terminals (UTF-8 and CP437) and, more
> importantly, the majority of real 6502 target machines.

... unless you live in Germany, where 7-bit ASCII wasn't enough even when
it was all you had ...

I agree with Mike that this looks like the Ü from Übersquirrel is causing
the problems; I won't be able to do anything for the next 12 hours or so,
but will change that to U and make a note in the README.txt. I never had
this problem, but then my setup is bilingual so I probably have something
running somewhere that copes with that.

Thanks for the save, Mike!

Y, Scot

## 

Scot W. Stevenson  -  scot.stevenson@gmail.com
Twitter: @scotstevenson - GitHub: https://github.com/scotws
Blog USA Erklärt: http://usaerklaert.wordpress.com
Blog BYO 8-Bit SBC: http://uebersquirrel.blogspot.de/

**Comment by scotws** [comment]
Removed umlaut, should produce "Ubersquirrel" now. Thanks!
